version: "3.9"

services:
  app:
    container_name: fur_app
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - "0.0.0.0:5555:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: on-failure

  postgres:
    container_name: fur_app_db
    image: "postgres:16.3"
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

