# Generated by Django 4.2.14 on 2024-07-20 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdiscount_product_favourite_for_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
