# Generated by Django 4.2.14 on 2024-07-20 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_productdiscount_discount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favourite_for_users',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
