# Generated by Django 4.2.14 on 2024-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_orderentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_price',
        ),
        migrations.AddField(
            model_name='orderentry',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
