# Generated by Django 4.2.14 on 2024-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_final_price_orderentry_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
