name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted

    env:
      POSTGRES_NAME: fur_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Compose
        run: docker compose up -d --build
