name: Deploy Dev

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted

    env:
      POSTGRES_NAME: fur_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      ENVIRONMENT: prod
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

      YDX_CLIENT_ID: 4fa9cb22324047cba05d3ffeab4deeb7
      YDX_CLIENT_SECRET: ${{ secrets.YDX_CLIENT_SECRET }}

      DEFAULT_FROM_EMAIL: ${{ secrets.EMAIL_USER }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_HOST: smtp.yandex.ru
      EMAIL_USE_SSL: True
      EMAIL_PORT: 465

      DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker Compose
        run: docker compose up -d --build
